export const ADD_WATCHLIST = 'ADD_WATCHLIST';
export const REMOVE_WATCHLIST = 'REMOVE_WATCHLIST';
export const GET_WATCHLIST_SUCCESS = 'GET_WATCHLIST_SUCCESS';

export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';

export const GET_STOCKS_SUCCESS = 'GET_STOCKS_SUCCESS';

export const FETCH_ALLOCATIONS_SUCCESS = 'FETCH_ALLOCATIONS_SUCCESS';

export const UPDATE_TICKER = 'UPDATE_TICKER';

export const FETCH_HISTORIC_PRICES_BEGIN = 'FETCH_HISTORIC_PRICES_BEGIN';
export const FETCH_HISTORIC_PRICES_SUCCESS = 'FETCH_HISTORIC_PRICES_SUCCESS';
//will make use of this failure case later on
export const FETCH_HISTORIC_PRICES_FAILURE = 'FETCH_HISTORIC_PRICES_FAILURE';
