export const ADD_WATCHLIST = "ADD_WATCHLIST";
export const REMOVE_WATCHLIST = "REMOVE_WATCHLIST";
export const GET_WATCHLIST_REQUEST = "GET_WATCHLIST_REQUEST";
export const GET_WATCHLIST_FAILURE = "GET_WATCHLIST_REQUEST";
export const GET_WATCHLIST_SUCCESS = "GET_WATCHLIST_SUCCESS";

export const TRANSACTION_REQUEST = "TRANSACTION_REQUEST";
export const TRANASCTION_FAILURE = "TRANSACTION_FAILURE";
export const TRANSACTION_SUCCESS = "TRANSACTION_SUCCESS";
export const GET_TRANSACTIONS_SUCCESS = "GET_TRANSACTIONS_SUCCESS";
export const ADD_TRANSACTION = "ADD_TRANSACTION"

export const GET_STOCKS_REQUEST = "GET_STOCKS_REQUEST";
export const GET_STOCKS_SUCCESS = "GET_STOCKS_SUCCESS";
export const GET_STOCKS_FAILURE = "GET_STOCKS_FAILURE";

export const FETCH_ALLOCATIONS_REQUEST = "FETCH_ALLOCATIONS_REQUEST";
export const FETCH_ALLOCATIONS_SUCCESS = "FETCH_ALLOCATIONS_SUCCESS";
export const FETCH_ALLOCATIONS_FAILURE = "FETCH_ALLOCATIONS_FAILURE";

